Функциональность "Удаление фильмов и пользователей" (Add remove endpoint)
palameda/java-filmorate pull request #10
Opened 2024-01-31 11:42 UTC by ISoldatov

Позволил себе немного доработать код (только для своих функций): 
- Изменил интерфейсы для методов удаления film и user.
- Добавил утильный класс CheckUtil что бы убрать дублирование кода при проверки.
- Проверку на нахождение сущности в БД вынес в сервисы.

2024-01-31 12:15 UTC, palameda requested changes
Отличная работа. Красиво и лаконично. 
Будет не лишним покрыть методы _deleteFilm_ и _deleteUser_ тестами.

2024-01-31 12:15 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/dao/implementation/FilmDbStorage.java
> +        return jdbcTemplate.update(sqlQuery, filmId) > 0;
Хорошее решение

2024-01-31 12:15 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/utils/CheckUtil.java
> +}
Хороший подход

2024-01-31 14:42 UTC, Advocat73 approved these changes

2024-02-01 06:58 UTC, ISoldatov commented
> Отличная работа. Красиво и лаконично. Будет не лишним покрыть методы _deleteFilm_ и _deleteUser_ тестами.

Спасибо. Тесты добавил.

2024-02-01 07:51 UTC, palameda approved these changes

2024-02-01 08:03 UTC, merged