Fit: создана функциональность создания и сохранения отзывов на фильмы
palameda/java-filmorate pull request #7
Opened 2024-01-30 14:35 UTC by Advocat73

Выполнена задача:
1. Создана сущность Review
2. Создан контроллер с эндпоинтами, связаннами с Review
3. Создан сервис и Dao
Обратите внимание, что лайки и дислайки на отзывы не проверяются на юзеры. В ТЗ и в постман я не увидел такой функциональности. Если ревьюер захочет, то быстро добавлю новую таблицу и реализуем эту функциональность.

2024-01-30 20:05 UTC, palameda requested changes
По функционалу замечаний нет. Реализация соответствует техническому заданию.
**Но следует дополнить:**
в реализации функциональности отсутствует логирование в классах _ReviewDaoImpl_, _ReviewService_, _ReviewController_

2024-01-30 20:05 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/dao/implementation/ReviewDaoImpl.java
> +    }
Отличное решение с сортировкой отзывов по рейтингу полезности

2024-01-30 20:05 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/dao/implementation/ReviewDaoImpl.java
> +public class ReviewDaoImpl implements ReviewDao {
Предлагаю добавить логирование в каждый метод класса

2024-01-30 20:05 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ReviewService.java
> +public class ReviewService {
Предлагаю добавить логирование в каждый метод класса

2024-01-30 20:05 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +public class ReviewController {
Предлагаю добавить логирование в каждый метод класса

2024-01-30 20:13 UTC, Advocat73 commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +public class ReviewController {
А у меня они были (логи), но я их убрал, т.к., наоборот посчитал, что после отладки только загрязняют код. Если что критичное, то исключения печатают ошибки.

2024-01-30 20:16 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +public class ReviewController {
С логированием сохраним общую стилистику в проекте

2024-01-30 20:18 UTC, Advocat73 commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +public class ReviewController {
Добавь в какой-нибудь метод лог, как ты хочешь. Я сделаю остальные по трафарету.

2024-01-30 20:28 UTC, palameda commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +public class ReviewController {
Достаточно будет покрыть методы с модификатором доступа public.
для хранилища - _log.info("ХРАНИЛИЩЕ: Получение пользователя по id {}", userId);_
для сервиса - _log.info("СЕРВИС: Отправлен запрос к хранилищу на получение пользователя по id {}", userId);_
для контроллера - _log.info("КОНТРОЛЛЕР: GET-запрос по эндпоинту /users/{}", id);_

2024-01-30 21:05 UTC, Advocat73 commented
Логи проставлены

2024-01-30 21:06 UTC, palameda approved these changes
Замечаний нет. Предлагаю принять реализованную функциональность в проект

2024-01-31 06:16 UTC, ISoldatov commented
Мне все понравилось, только предлагаю использовать уже принятые в проекте наименования ReviewDaoImpl переименовать в ReviewDbStorage. То же и с названием интерфейса.

2024-01-31 06:39 UTC, Advocat73 commented
Переименовал

2024-01-31 08:18 UTC, ISoldatov approved these changes

2024-01-31 08:21 UTC, merged